// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJdQq2es9aVCmyQ2pVA8iAs3l8iGraMQY',
    appId: '1:952176293225:web:a87aee33346f2c75b779f8',
    messagingSenderId: '952176293225',
    projectId: 'invernadero-luis',
    authDomain: 'invernadero-luis.firebaseapp.com',
    databaseURL: 'https://invernadero-luis-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-luis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7DDfPtW1qjgdLdgd630sb_tvmtrpYBiI',
    appId: '1:952176293225:android:3417a2ea58418a2db779f8',
    messagingSenderId: '952176293225',
    projectId: 'invernadero-luis',
    databaseURL: 'https://invernadero-luis-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-luis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6bp-xmh_7OxbOj9gMxgWDEO6uWnPYNk',
    appId: '1:952176293225:ios:4274dfb104a4c0c2b779f8',
    messagingSenderId: '952176293225',
    projectId: 'invernadero-luis',
    databaseURL: 'https://invernadero-luis-default-rtdb.firebaseio.com',
    storageBucket: 'invernadero-luis.firebasestorage.app',
    iosBundleId: 'com.invernadero-luis.app',
  );
}
